### ISSUE TITLE
Неправильная нумерация записей

### ISSUE THREAD

**Issue by ping335** [Ceredira/CerediraTess#10]
Шаги:
- Создать 3 записи (например)
- Удалить вторую запись
- Нажать на глазик у последней записи (она теперь вторая. И записей всего 2, т.к. ту что посередине удалили)
Но почему то она указана как 3я запись -   "Просмотр записи # 3"

Возможно, это дефект.

**Comment by unixshaman** [comment]
Это не дефект, так как это число - не порядковый номер записи, а ее уникальный идентификационный номер (id). При создании записи это число инкремент (+1) от последнего номера в этой таблице.
