### ISSUE TITLE
Две кнопки выполняют одни и те же действия

### ISSUE THREAD

**Issue by ping335** [Ceredira/CerediraTess#13]
При дублировании записи скрипта (позитивный сценарий)

1. Создать скрипт
2. Нажать на иконку дубликата "Dublicate Row"
3. В поле "Имя скрипта" ввести имя дубликата 

При нажатии на кнопку  "Сохранить и добавить новый объект"
или на кнопку "Сохранить и продолжить редактирование" происходят одни и те же действия

И в первом и во втором случае, создается дубликат записи и не происходит перенаправления ко всем записям.

**Comment by unixshaman** [comment]
Не согласен с этим дефектом. При нажатии на кнопку "Сохранить и добавить новый объект" - мы остаемся на странице с тем объектом - который дублировали.
А при нажатии на кнопку "Сохранить и продолжить редактирование" - мы переходим на страницу редактирования созданного объекта, для возможности его дальнейшего изменения.
