### ISSUE TITLE
Нельзя посмотреть информаю о полях "Агенты" и "Users"   в ролях

### ISSUE THREAD

**Issue by ping335** [Ceredira/CerediraTess#15]
При создании и редактировании записи роли можно выбрать поле "Агенты" и "Users", но потом эти поля нигде не отображаются. Т.е. если нажать на иконку "глазика" отображается только "Название роли " и "Описание". Можно также добавить туда такие поля как  "Агенты" и "Users" (т.е чтобы все заполненные поля отображались)

Их можно  увидеть только если опять нажать на "Редактировать запись". Наверно это неправильно.

**Comment by unixshaman** [comment]
Additional fix in https://github.com/Ceredira/CerediraTess/commit/928db03ce600e30828acb29022d2bea200deacf8
