### ISSUE TITLE
Чекбокс "Блокировка", при создании пользователя, стал по умолчанию не активным

### ISSUE THREAD

**Issue by ping335** [Ceredira/CerediraTess#38]
При создании нового пользователя:

1. Войти на сайт с пользователем "admin"
1. В главном меню перейти в раздел "Администрирование -> Пользователи"
1. Выбрать вкладку "Создать"
1. Ввести обязательные поля:
    1. В поле "Логин пользователя" ввести значение "test"
    1. В поле "Пароль" ввести значение "test"
1. Отметить checkbox "Блокировка", если он не отмечен

Если его не отметить, что невозможно будет под таким пользователем войти в систему.

**Comment by unixshaman** [comment]
Предлагаю чекбокс "Блокировка" переименовать в "Активный", так хотя бы будет соответствовать выполняемому функционалу.
