### ISSUE TITLE
Поменять текст сообщения под полем Имя скрипта в модальном окне Создать новую запись

### ISSUE THREAD

**Issue by Elvira333** [Ceredira/CerediraTess#47]
**Предусловия:** 
Авторизоваться (логин-admin, пароль-admin).
Перейти в раздел администрирование -> скрипты.

**Окружение:**
Google Chrome Версия 100.0.4896.127 (Официальная сборка), (64 бит)
ОС - Windows 10, 64 бит
CerediraTess-v0.6.0

**Шаги:**
1. Нажать кнопку "Создать"
2. Открывается модальное окно Создать новую запись.
3. Отображается поле Имя скрипта
4. Отображается поле Описание

**Фактический результат:**

Под полем Имя скрипта сообщение с текстом "Путь к исполняемому файлу от каталога scripts"

**Ожидаемый результат:**

Под полем Имя скрипта сообщение с текстом "Путь к исполняемому файлу от каталога scripts" 
дополненное примером, для удобства пользователя

**Comment by unixshaman** [comment]
Аналогичный дефект уже был: #7 
Реализацию можно посмотреть в #20 
Вошло в релиз https://github.com/Ceredira/CerediraTess/releases/tag/v0.6.0
