### ISSUE TITLE
При обновлении страницы, все заполненные поля исчезают

### ISSUE THREAD

**Issue by ping335** [Ceredira/CerediraTess#49]
Шаги:
1. Пользователь авторизован
1. Роль текущего пользователя равна "admin"
1. В главном меню перейти в раздел "Администрирование -> Пользователи"
1. Выбрать вкладку "Создать"
1. Появилось модальное диалоговое "Создать новую запись"
1. Заполнить все поля значениями: 
    1. В поле "Логин пользователя" ввести значение "test"
    1. В поле "Почта" ввести значение "test@mail.ru"
    1. В поле " Имя пользователя" ввести значение "test"
    1. В поле "Роли" ввести значение "admin"
    1. В поле "Пароль" ввести значение "123"
    1. В поле "Подтверждение пароля" ввести значение "123"
1. Нажать на кнопку F5 на клавиатуре (обновить текущую страницу)
1. Модальное диалоговое окно со всеми заполненными данными исчезло

### **Фактический результат:**
Модальное диалоговое окно со всеми заполненными данными исчезло

### **Ожидаемый результат:**
Модальное диалоговое окно со всеми заполненными данными осталось как было до обновления страницы. Все введенные данные кроме полей  "Пароль" и "Подтверждение пароля" не исчезли.

Аналогичная ситуация происходит также при создании Агентов, Скриптов, Ролей и  Типов ОС.

**Comment by unixshaman** [comment]
Фактический результат соответствует изначально архитектурно запланированному поведению. Т.е. клиент загрузил страницу, выполнил любые манипуляции в UI, без нажатия кнопки Сохранить (или аналогичных кнопок в целом по сайту), никакие изменения применены не будут. При обновлении страницы происходит получение страницы в первоначальном ее состоянии. 
Вводимых данных не на столько много, и они не на столько важны, чтобы закладываться на сохранение действий пользователя и их восстановлении при обновлениях страниц. Просто так F5 или обновление страницы обычных пользователь по середине бизнес-сценариев не нажимает. Реализация такого поведения требует существенных затрат, чего не планируются в текущий момент времени и ближайшем будущем.

**Comment by ping335** [comment]
> Просто так F5 или обновление страницы обычных пользователь по середине бизнес-сценариев не нажимает.

Мне пришлось обновить страницу как раз по середине заполнения, потому что иначе необходимые для продолжения данные не отображались

Шаги:
1. Пользователь авторизован
1. Роль текущего пользователя равна "admin"
1. В главном меню перейти в раздел "Администрирование -> Агенты"
1. Нажать на вкладку "Создать"
1. Заполнить все поля до выбора скрипта
1. В выпадающем списке "Скрипты" выбрать скрипт
1. В выпадающем списке отображается значение "No matches found"
1. Перейти в другой вкладке в раздел "Скрипты" для  создания скрипта
2.  Создать скрипт
3. Вернуть во вкладку с созданием агента
4. В поле "Скрипты" по прежнему  отображается значение "No matches found"
5. Нажать на F5
6. В поле "Скрипты" появился созданный скрипт, однако все остальные поля пропали

Думаю, это можно решить добавив в "Скрипты" скрипт по умолчанию, чтобы его можно было выбрать без необходимости переходить во вкладку и создавать

**Comment by unixshaman** [comment]
Я думаю, что это лучше решить правильно отсортировав в меню Администрирования сущности для создания, чтобы видно было, что сначала надо создать скрипты, потом другие базовые вещи, а потом уже сложные вещи.

**Comment by unixshaman** [comment]
Да, я подтверждаю что я тоже сталкивался с такой необходимостью, но я сохранял объект агента, создавал скрипт, возвращался в агент и продолжал его редактирование, но не делал обновления.
