### ISSUE TITLE
Поменять название поля "Agents" на "Агенты" при создании нового типа ОС

### ISSUE THREAD

**Issue by ping335** [Ceredira/CerediraTess#51]
Окружение:

    -     Google Chrome Версия 101.0.4951.67 (Официальная сборка), (64 бит)
    -     ОС - Windows 10, 64 бит
    -     CerediraTess-v0.6.0

Шаги:

1. Войти на сайт с пользователем "admin"
2. В главном меню перейти в раздел "Администрирование -> Типы ОС"
3. Нажать на вкладку "Создать"
4. Название поля  "Имя ОС" написано по-русски
5. Название поля  "Agents" написано по-английски

Ожидаемый результат: все поля написаны по-русски

**Comment by unixshaman** [comment]
Решил, что поле Агенты, вообще не должно быть доступно для просмотра и редактирования в разделе создания Типов ОС. Это ломает внутреннюю логику работы. При необходимости выполнения такой задачи, надо пользоваться сущностью Агенты, и там отсортировать список агентов по столбцу Тип ОС.

Поле убрано в задаче; #56
