### ISSUE TITLE
поехала форма(login, password) при вводе не валидных данных

### ISSUE THREAD

**Issue by RadostDudhi** [Ceredira/CerediraTess#60]
https://drive.google.com/file/d/1kN2jaYqxqYjs6le3pgJ4mqLLjpLO2hm_/view?usp=sharing

**Comment by unixshaman** [comment]
В  коммите https://github.com/Ceredira/CerediraTess/commit/d0717a9c55b9ea18c0b1047e776c1f45cd29b504 исправлено.
Неверный пароль пользователя:
![image](https://github.com/Ceredira/CerediraTess/assets/1523779/4f3a2ceb-bbda-4294-8198-e7744cf09d11)

Несуществующий логин:
![image](https://github.com/Ceredira/CerediraTess/assets/1523779/e5b61edb-c346-4b9c-a447-6593b15aa4cf)
