### ISSUE TITLE
не кликабельный "Х" в поле "логин пользователя"

### ISSUE THREAD

**Issue by RadostDudhi** [Ceredira/CerediraTess#61]
**Steps:**"Администрирование -> Пользователи"->"Создать"->Ввести логин существующего пользователя
**AR:** При клике на "Х" -> поле "логин пользователя" очищается
**Screen:**(https://drive.google.com/file/d/1a3_e5O9nX1bvIRS5S3MtM2Qxuk8Wnfr2/view?usp=sharing)

**Comment by unixshaman** [comment]
Этот крестик не для удаления содержимого поля, а как пометка, что поле не проходит валидацию. Не баг.
